language: node_js
nodejs:
- 12.18.1
cache:
  directories:
  - node_modules
notifications:
  email:
    onfailure: change
    onsuccess: change
addons:
  sshknownhosts:
  - 161.35.235.65
branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/var/www/build.jesusamador.com/
  - REMOTEUSER=travis
  - REMOTEHOST=161.35.235.65
  - PORT=8080
# before_install:
# - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
#   -in travis_rsa.enc -out travis_rsa -d
# - chmod 600 travis_rsa
# - mv travis_rsa ~/.ssh/id_rsa
install: 
before_script: 
script:
- npm run build
after_success:
- "./scripts/deploy.sh"
