language: node_js
nodejs:
- 12.18.1
cache:
  directories:
  - node_modules
notifications:
  email:
    onfailure: change
    onsuccess: change
addons:
  sshknownhosts:
  - 161.35.235.65
branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/var/www/build.jesusamador.com/
  - REMOTEUSER=travis
  - REMOTEHOST=161.35.235.65
  - PORT=8080

before_install:
  - openssl aes-256-cbc -K $encrypted_e6cc0fb2b8da_key -iv $encrypted_e6cc0fb2b8da_iv
  -in travis.enc -out travis -d
  - chmod 600 travis
  - mv travis ~/.ssh/id_rsa
install: 
before_script: 
script:
- npm run build
after_success:
- "./scripts/deploy.sh"
